package oracle.fod.storefront.module.client;

import oracle.fod.storefront.module.common.FODCheckoutAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 09:14:18 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FODCheckoutAMClient extends ApplicationModuleImpl implements FODCheckoutAM {
    /**
     * This is the default constructor (do not remove).
     */
    public FODCheckoutAMClient() {
    }

    public void init() {
        Object _ret = this.riInvokeExportedMethod(this,"init",null,null);
        return;
    }
}
