package oracle.fod.storefront.module.client;

import oracle.fod.storefront.module.common.FODProductAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 09:16:59 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FODProductAMClient extends ApplicationModuleImpl implements FODProductAM {
    /**
     * This is the default constructor (do not remove).
     */
    public FODProductAMClient() {
    }

    public void setCurrentCategory(Number categoryId, Number subCategoryId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setCurrentCategory",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {categoryId, subCategoryId});
        return;
    }
}
