package oracle.fod.storefront.test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 18 14:19:42 MDT 2008
// ---------------------------------------------------------------------
public interface TestAM extends ApplicationModule {
    void init();
}
