package oracle.fod.storefront.entity;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 09:48:52 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountryEOImpl extends BaseEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        IsoCountryCode {
            public Object get(CountryEOImpl obj) {
                return obj.getIsoCountryCode();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setIsoCountryCode((String)value);
            }
        }
        ,
        CountryName {
            public Object get(CountryEOImpl obj) {
                return obj.getCountryName();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setCountryName((String)value);
            }
        }
        ,
        Language {
            public Object get(CountryEOImpl obj) {
                return obj.getLanguage();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setLanguage((String)value);
            }
        }
        ,
        SourceLang {
            public Object get(CountryEOImpl obj) {
                return obj.getSourceLang();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setSourceLang((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CountryEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(CountryEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CountryEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CountryEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(CountryEOImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(CountryEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CountryEOImpl object);

        public abstract void put(CountryEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ISOCOUNTRYCODE = AttributesEnum.IsoCountryCode.index();
    public static final int COUNTRYNAME = AttributesEnum.CountryName.index();
    public static final int LANGUAGE = AttributesEnum.Language.index();
    public static final int SOURCELANG = AttributesEnum.SourceLang.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CountryEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("oracle.fod.storefront.entity.CountryEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for IsoCountryCode, using the alias name IsoCountryCode.
     * @return the IsoCountryCode
     */
    public String getIsoCountryCode() {
        return (String)getAttributeInternal(ISOCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsoCountryCode.
     * @param value value to set the IsoCountryCode
     */
    public void setIsoCountryCode(String value) {
        setAttributeInternal(ISOCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for CountryName, using the alias name CountryName.
     * @return the CountryName
     */
    public String getCountryName() {
        return (String)getAttributeInternal(COUNTRYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryName.
     * @param value value to set the CountryName
     */
    public void setCountryName(String value) {
        setAttributeInternal(COUNTRYNAME, value);
    }

    /**
     * Gets the attribute value for Language, using the alias name Language.
     * @return the Language
     */
    public String getLanguage() {
        return (String)getAttributeInternal(LANGUAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Language.
     * @param value value to set the Language
     */
    public void setLanguage(String value) {
        setAttributeInternal(LANGUAGE, value);
    }

    /**
     * Gets the attribute value for SourceLang, using the alias name SourceLang.
     * @return the SourceLang
     */
    public String getSourceLang() {
        return (String)getAttributeInternal(SOURCELANG);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceLang.
     * @param value value to set the SourceLang
     */
    public void setSourceLang(String value) {
        setAttributeInternal(SOURCELANG, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param isoCountryCode key constituent
     * @param language key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String isoCountryCode,
                                       String language) {
        return new Key(new Object[]{isoCountryCode, language});
    }

}
