package oracle.fod.storefront.entity;

import oracle.fod.storefront.domain.common.PhoneNumber;

import oracle.jbo.Key;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 08 16:22:39 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SupplierEOImpl extends BaseEntityImpl {
    private static EntityDefImpl mDefinitionObject;


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SupplierId {
            public Object get(SupplierEOImpl obj) {
                return obj.getSupplierId();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setSupplierId((DBSequence)value);
            }
        }
        ,
        SupplierName {
            public Object get(SupplierEOImpl obj) {
                return obj.getSupplierName();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setSupplierName((String)value);
            }
        }
        ,
        SupplierStatus {
            public Object get(SupplierEOImpl obj) {
                return obj.getSupplierStatus();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setSupplierStatus((String)value);
            }
        }
        ,
        PhoneNumber {
            public Object get(SupplierEOImpl obj) {
                return obj.getPhoneNumber();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setPhoneNumber((String)value);
            }
        }
        ,
        Email {
            public Object get(SupplierEOImpl obj) {
                return obj.getEmail();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        UiSkin {
            public Object get(SupplierEOImpl obj) {
                return obj.getUiSkin();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setUiSkin((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(SupplierEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(SupplierEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(SupplierEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(SupplierEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(SupplierEOImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LookupCodeVVO1 {
            public Object get(SupplierEOImpl obj) {
                return obj.getLookupCodeVVO1();
            }

            public void put(SupplierEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SupplierEOImpl object);

        public abstract void put(SupplierEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SUPPLIERID = AttributesEnum.SupplierId.index();
    public static final int SUPPLIERNAME = AttributesEnum.SupplierName.index();
    public static final int SUPPLIERSTATUS = AttributesEnum.SupplierStatus.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int UISKIN = AttributesEnum.UiSkin.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();

    public static final int LOOKUPCODEVVO1 = AttributesEnum.LookupCodeVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SupplierEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("oracle.fod.storefront.entity.SupplierEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for SupplierId, using the alias name SupplierId.
     * @return the SupplierId
     */
    public DBSequence getSupplierId() {
        return (DBSequence)getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierId.
     * @param value value to set the SupplierId
     */
    public void setSupplierId(DBSequence value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for SupplierName, using the alias name SupplierName.
     * @return the SupplierName
     */
    public String getSupplierName() {
        return (String)getAttributeInternal(SUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierName.
     * @param value value to set the SupplierName
     */
    public void setSupplierName(String value) {
        setAttributeInternal(SUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for SupplierStatus, using the alias name SupplierStatus.
     * @return the SupplierStatus
     */
    public String getSupplierStatus() {
        return (String)getAttributeInternal(SUPPLIERSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierStatus.
     * @param value value to set the SupplierStatus
     */
    public void setSupplierStatus(String value) {
        setAttributeInternal(SUPPLIERSTATUS, value);
    }

    /**
     * Gets the attribute value for PhoneNumber, using the alias name PhoneNumber.
     * @return the PhoneNumber
     */
    public String getPhoneNumber() {
        return (String)getAttributeInternal(PHONENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhoneNumber.
     * @param value value to set the PhoneNumber
     */
    public void setPhoneNumber(String value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the Email
     */
    public String getEmail() {
        return (String)getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for UiSkin, using the alias name UiSkin.
     * @return the UiSkin
     */
    public String getUiSkin() {
        return (String)getAttributeInternal(UISKIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for UiSkin.
     * @param value value to set the UiSkin
     */
    public void setUiSkin(String value) {
        setAttributeInternal(UISKIN, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupCodeVVO1.
     */
    public RowSet getLookupCodeVVO1() {
        return (RowSet)getAttributeInternal(LOOKUPCODEVVO1);
    }

    /**
     * @param supplierId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence supplierId) {
        return new Key(new Object[]{supplierId});
    }


}
