package oracle.fod.storefront.entity;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 10:12:40 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WarehouseEOImpl extends BaseEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        WarehouseId {
            public Object get(WarehouseEOImpl obj) {
                return obj.getWarehouseId();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setWarehouseId((Number)value);
            }
        }
        ,
        AddressId {
            public Object get(WarehouseEOImpl obj) {
                return obj.getAddressId();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAddressId((Number)value);
            }
        }
        ,
        WarehouseName {
            public Object get(WarehouseEOImpl obj) {
                return obj.getWarehouseName();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setWarehouseName((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WarehouseEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(WarehouseEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WarehouseEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(WarehouseEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(WarehouseEOImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Address {
            public Object get(WarehouseEOImpl obj) {
                return obj.getAddress();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAddress((AddressEOImpl)value);
            }
        }
        ,
        WarehouseStockLevel {
            public Object get(WarehouseEOImpl obj) {
                return obj.getWarehouseStockLevel();
            }

            public void put(WarehouseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WarehouseEOImpl object);

        public abstract void put(WarehouseEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int WAREHOUSEID = AttributesEnum.WarehouseId.index();
    public static final int ADDRESSID = AttributesEnum.AddressId.index();
    public static final int WAREHOUSENAME = AttributesEnum.WarehouseName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int WAREHOUSESTOCKLEVEL = AttributesEnum.WarehouseStockLevel.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WarehouseEOImpl() {
    }

    /**
     * Gets the attribute value for WarehouseId, using the alias name WarehouseId.
     * @return the WarehouseId
     */
    public Number getWarehouseId() {
        return (Number)getAttributeInternal(WAREHOUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarehouseId.
     * @param value value to set the WarehouseId
     */
    public void setWarehouseId(Number value) {
        setAttributeInternal(WAREHOUSEID, value);
    }

    /**
     * Gets the attribute value for AddressId, using the alias name AddressId.
     * @return the AddressId
     */
    public Number getAddressId() {
        return (Number)getAttributeInternal(ADDRESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressId.
     * @param value value to set the AddressId
     */
    public void setAddressId(Number value) {
        setAttributeInternal(ADDRESSID, value);
    }

    /**
     * Gets the attribute value for WarehouseName, using the alias name WarehouseName.
     * @return the WarehouseName
     */
    public String getWarehouseName() {
        return (String)getAttributeInternal(WAREHOUSENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarehouseName.
     * @param value value to set the WarehouseName
     */
    public void setWarehouseName(String value) {
        setAttributeInternal(WAREHOUSENAME, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity AddressEOImpl.
     */
    public AddressEOImpl getAddress() {
        return (AddressEOImpl)getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as the associated entity AddressEOImpl.
     */
    public void setAddress(AddressEOImpl value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getWarehouseStockLevel() {
        return (RowIterator)getAttributeInternal(WAREHOUSESTOCKLEVEL);
    }

    /**
     * @param warehouseId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number warehouseId) {
        return new Key(new Object[]{warehouseId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("oracle.fod.storefront.entity.WarehouseEO");
        }
        return mDefinitionObject;
    }
}
