package oracle.fod.storefront.entity;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 10:13:03 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WarehouseStockLevelEOImpl extends BaseEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ProductId {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getProductId();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setProductId((Number)value);
            }
        }
        ,
        WarehouseId {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getWarehouseId();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setWarehouseId((Number)value);
            }
        }
        ,
        QuantityOnHand {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getQuantityOnHand();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setQuantityOnHand((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Warehouse {
            public Object get(WarehouseStockLevelEOImpl obj) {
                return obj.getWarehouse();
            }

            public void put(WarehouseStockLevelEOImpl obj, Object value) {
                obj.setWarehouse((WarehouseEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WarehouseStockLevelEOImpl object);

        public abstract void put(WarehouseStockLevelEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int WAREHOUSEID = AttributesEnum.WarehouseId.index();
    public static final int QUANTITYONHAND = AttributesEnum.QuantityOnHand.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int WAREHOUSE = AttributesEnum.Warehouse.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WarehouseStockLevelEOImpl() {
    }

    /**
     * Gets the attribute value for ProductId, using the alias name ProductId.
     * @return the ProductId
     */
    public Number getProductId() {
        return (Number)getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductId.
     * @param value value to set the ProductId
     */
    public void setProductId(Number value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for WarehouseId, using the alias name WarehouseId.
     * @return the WarehouseId
     */
    public Number getWarehouseId() {
        return (Number)getAttributeInternal(WAREHOUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarehouseId.
     * @param value value to set the WarehouseId
     */
    public void setWarehouseId(Number value) {
        setAttributeInternal(WAREHOUSEID, value);
    }

    /**
     * Gets the attribute value for QuantityOnHand, using the alias name QuantityOnHand.
     * @return the QuantityOnHand
     */
    public Number getQuantityOnHand() {
        return (Number)getAttributeInternal(QUANTITYONHAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for QuantityOnHand.
     * @param value value to set the QuantityOnHand
     */
    public void setQuantityOnHand(Number value) {
        setAttributeInternal(QUANTITYONHAND, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity WarehouseEOImpl.
     */
    public WarehouseEOImpl getWarehouse() {
        return (WarehouseEOImpl)getAttributeInternal(WAREHOUSE);
    }

    /**
     * Sets <code>value</code> as the associated entity WarehouseEOImpl.
     */
    public void setWarehouse(WarehouseEOImpl value) {
        setAttributeInternal(WAREHOUSE, value);
    }

    /**
     * @param productId key constituent
     * @param warehouseId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number productId, Number warehouseId) {
        return new Key(new Object[]{productId, warehouseId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("oracle.fod.storefront.entity.WarehouseStockLevelEO");
        }
        return mDefinitionObject;
    }
}
