package oracle.fod.storefront.test.client;

import oracle.fod.storefront.test.common.TestAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 18 14:19:42 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestAMClient extends ApplicationModuleImpl implements TestAM {
    /**
     * This is the default constructor (do not remove).
     */
    public TestAMClient() {
    }

    public void init() {
        Object _ret = this.riInvokeExportedMethod(this,"init",null,null);
        return;
    }
}
