package oracle.fod.storefront.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 09:14:18 MDT 2008
// ---------------------------------------------------------------------
public interface FODCheckoutAM extends ApplicationModule {
    void init();
}
