package oracle.fod.storefront.module.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 09 09:16:59 MDT 2008
// ---------------------------------------------------------------------
public interface FODProductAM extends ApplicationModule {
    void setCurrentCategory(Number categoryId, Number subCategoryId);
}
