package oracle.fod.storefront.module.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 08 17:16:42 MDT 2008
// ---------------------------------------------------------------------
public interface FODShoppingCartAM extends ApplicationModule {
    void init();

    void addItemToCart(Number productId);

    String getUserName();

    boolean isUserInRole(String role);
}
